# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vtlinux-base-release"
BBFILE_PATTERN_meta-vtlinux-base-release := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vtlinux-base-release = "7"
LAYERSERIES_COMPAT_meta-vtlinux-base-release = "scarthgap"
