#!/bin/sh

set -e
#改ID
vendor=0x18d1
product=0xD002
manufacturer=TI
model="AM62L"
serial=77777777

[ -d /sys/kernel/config/usb_gadget ] || modprobe libcomposite

cd /sys/kernel/config/usb_gadget

[ -d adb ] && /usr/bin/android-gadget-cleanup || true

mkdir adb
cd adb

mkdir configs/c.1
mkdir functions/ffs.usb0
mkdir strings/0x409
mkdir configs/c.1/strings/0x409
echo -n "$vendor" > idVendor
echo -n "$product" > idProduct
echo "$serial" > strings/0x409/serialnumber
echo "$manufacturer" > strings/0x409/manufacturer
echo "$model" > strings/0x409/product
echo "adb" > configs/c.1/strings/0x409/configuration
ln -s functions/ffs.usb0 configs/c.1

mkdir -p /dev/usb-ffs/adb
mount -t functionfs usb0 /dev/usb-ffs/adb
