
require conf/machine/include/am62lxx.inc
require conf/machine/include/ti-extras.inc
require include/vt-am62l.inc

IMAGE_FSTYPES = "tar.xz ext4 ext4.gz wic"


KERNEL_DEVICETREE_PREFIX = " \
    ti/vt-sbc- \
"

KERNEL_DEVICETREE = "am62l.dtb"

UBOOT_MACHINE = "vt_sbc_am62l_defconfig"
PREFERRED_PROVIDER_android-tools-conf = "android-tools-conf-ti"



#############################################
# Copyright vantron 2025
#############################################
IMAGE_VERSION ?= "1.0.6"
HW_VERSION ?= "1.0"
LINUX_VERSION = "6.12.24"
CUSTOM_APP ?= "xxxxx"
APP_VERSION ?= "xxxx"
FACTORY_IMAGE ?= "vtlinux-image-weston"
#############################################

