#!/bin/sh
#
### BEGIN INIT INFO
# Provides: emptty
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     5
# Default-Stop:      0 1 2 3 6
# X-Interactive: true
### END INIT INFO

PIDFILE=/var/run/emptty.pid

# source function library
. /etc/init.d/functions

case "$1" in
	start)
		echo "Starting display manager: emptty"
		start-stop-daemon -b -S -p $PIDFILE -x /usr/bin/emptty -- -d
		;;
	stop)
		echo "Stopping display manager: emptty"
		start-stop-daemon -K -p $PIDFILE -x /usr/bin/emptty
		;;
	restart)
		start-stop-daemon -K -p $PIDFILE --oknodo -x /usr/bin/emptty -- -d
		sleep 2
		start-stop-daemon -b -S -p $PIDFILE -x /usr/bin/emptty
		;;
	reload|force-reload)
		start-stop-daemon -K -p $PIDFILE -s 1 -x /usr/bin/emptty
		;;
	status)
		status /usr/bin/emptty
		;;
	*)
		echo "usage: $0 { start | stop | restart }"
		;;
esac
